DATA_PATH = "../data/"
ONTOBIOTOPE_FILE_PATH = DATA_PATH + "OntoBiotope_BioNLP-OST-2019.obo"
DEV_PATH = DATA_PATH + "BioNLP-OST-2019_BB-norm_dev/"
DEV_FILES = DEV_PATH + "*.a1"
DEV_LABELS = DEV_PATH + "*.a2"
DEV_TXT_FILES = DEV_PATH + "*.txt"
OUTPUT_PATH = "../predictions/"