DATA_PATH = "../data/"
ONTOBIOTOPE_FILE_PATH = DATA_PATH + "OntoBiotope_BioNLP-OST-2019.obo"

DEV_PATH = DATA_PATH + "BioNLP-OST-2019_BB-norm_dev/"
DEV_FILES = DEV_PATH + "*.a1"
DEV_LABELS = DEV_PATH + "*.a2"
DEV_TXT_FILES = DEV_PATH + "*.txt"

TRAIN_PATH = DATA_PATH + "BioNLP-OST-2019_BB-norm_train/"
TRAIN_FILES = TRAIN_PATH + "*.a1"
TRAIN_LABELS = TRAIN_PATH + "*.a2"
TRAIN_TXT_FILES = TRAIN_PATH + "*.txt"

TEST_PATH = DATA_PATH + "BioNLP-OST-2019_BB-norm_test/"
TEST_TXT_FILES = TEST_PATH + "*.txt"
TEST_FILES = TEST_PATH + "*.a1"

OUTPUT_PATH = "../predictions/"


